### ISSUE TITLE
python client fail to create cluster node using hazhalcast service 

### ISSUE THREAD

**Issue by vaibhavpatil123** [hazelcast/hazelcast-python-client#170]
Using code https://hazelcast.com/blog/getting-started-python-client/ ref 
we are not able to connect to cluseter 

getting below exception 
    self._connect_to_cluster()
  File "C:\Users\vapa1115\AppData\Local\Programs\Python\Python37\lib\site-packages\hazelcast\cluster.py", line 142, in _connect_to_cluster
    raise HazelcastError(error_msg)
hazelcast.exception.HazelcastError: Could not connect to any of [Address(host=127.0.0.1, port=5701), Address(host=127.0.0.1, port=5702), Address(host=127.0.0.1, port=5703)] after 2 tries

Process finished with exit code 1

Code :

config = hazelcast.ClientConfig()
client = hazelcast.HazelcastClient(config)

**Comment by mdumandag** [comment]
Hi @vaibhavpatil123 
Are the Hazelcast members are active when you encountered this error ? If so, can you share the logs of them ?

**Comment by vaibhavpatil123** [comment]
> Hi @vaibhavpatil123
> Are the Hazelcast members are active when you encountered this error ? If so, can you share the logs of them ?

Not clear your question.

Also I want to know does cluster we cant run with python client ?? 
Do we need to make avaliable cluster running in other location?

How we can run python hazhal cast cluster node?

**Comment by mdumandag** [comment]
@vaibhavpatil123, you need to have at least one running Hazelcast member before using the client. 

You can take a look at the [Working with Hazelcast IMDG Clusters](https://github.com/hazelcast/hazelcast-python-client#12-working-with-hazelcast-imdg-clusters) section of the README to start the Hazelcast member. 

After starting the member, Python client should be able to connect to the cluster.

**Comment by vaibhavpatil123** [comment]
Our application is python flask application and running in docker/openshift.
How we can run that instance ? 

> My question is - is there is any way can run hazalcast cluster in python application ?????

**Comment by vaibhavpatil123** [comment]
As in spring boot application we can configure and run cluster using code 
like below 

@Bean
    public Config hazelCastConfig(){
        return new Config()
                .setInstanceName("hazelcast-instance")
                .addMapConfig(
                        new MapConfig()
                                .setName("employees")
                                .setMaxSizeConfig(new MaxSizeConfig(200, MaxSizeConfig.MaxSizePolicy.FREE_HEAP_SIZE))
                                .setEvictionPolicy(EvictionPolicy.LRU)
                                .setTimeToLiveSeconds(20));
    }


Is there any same code in python????

**Comment by vaibhavpatil123** [comment]
https://github.com/hazelcast/hazelcast-code-samples/blob/master/cluster/src/main/java/PromoteLiteMember.java

**Comment by mdumandag** [comment]
You cannot start the Hazelcast member within the Python client. You should configure and start your cluster before starting the client. 

See the documentation for the [Hazelcast for Openshift](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift) to start the Hazelcast cluster. 

Then, configure your python client as described in [this](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift#external-hazelcast-client) section.
Same configuration for the Python client would be like this.
```python
config.network_config.smart_routing = False
config.network_config.addresses.append("192.168.1.176:31296")
```

**Comment by vaibhavpatil123** [comment]
Thanks for reply!!! 
what is Ibelow P/PORT ? 
 192.168.1.176:31296

**Comment by mdumandag** [comment]
This is the IP:Port of the Hazelcast member. You can get these values for your cluster following the steps described in the [External Hazelcast Client
](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift#external-hazelcast-client) section.

**Comment by vaibhavpatil123** [comment]
Thanks for information , I will check things now closing this defect
