### ISSUE TITLE
RINGBUFFER_SERIVCE typo in proxy

### ISSUE THREAD

**Issue by filipArena** [hazelcast/hazelcast-python-client#193]
This one is non-critical since the same typo is used across all references in the codebase.

https://github.com/hazelcast/hazelcast-python-client/blob/b34b93d866369578c2c111c6659183962907eafe/hazelcast/proxy/__init__.py#L32

Should be SER**VICE** in [hazelcast/proxy/\_\_init\_\_.py](https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/proxy/__init__.py#L32) in `master`.

**Comment by burakcelebi** [comment]
Thank you, @filipArena! Nice catch!
