### ISSUE TITLE
ReliableTopic for Python

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-python-client#201]
Currently, the Python client lacks Hazelcast's ReliableTopic:
https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#reliable-topic

Hazelcast's Reliable Topic uses the same [Topic](https://github.com/hazelcast/hazelcast-python-client#748-using-topic) interface as a regular topic. The main difference is that Reliable Topic is backed up by the [Ringbuffer](https://github.com/hazelcast/hazelcast-python-client#747-using-ringbuffer) data structure, a replicated but not partitioned data structure that stores its data in a ring-like structure.

**Comment by buraksezer** [comment]
Hello,

I would like to take this issue.

**Comment by burakcelebi** [comment]
Great, thanks @buraksezer! 

We are always here to help you :) cc: @asimarslan, @mdumandag

**Comment by mdumandag** [comment]
Closing this, as the feature is implemented by

https://github.com/hazelcast/hazelcast-python-client/pull/395
