### ISSUE TITLE
Paging Predicate

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-python-client#202]
Currently, the Python client does not support Hazelcast's [paging predicates](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#filtering-with-paging-predicates)

**Comment by yuce** [comment]
@mdumandag This feature seems to be already implemented. Are we missing anything?

**Comment by mdumandag** [comment]
No, it is also forward ported to the 4.x branch. Let me close this
