### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-python-client#203]
The Python client lacks Projection support for queries.

There are cases where instead of sending all the data returned by a query from a member, you want to transform (strip down) each result object in order to avoid redundant network traffic. For example, you select all employees based on some criteria, but you just want to return their name instead of the whole Employee object. It is easily doable with the Projection API.

For further information, see 
https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#projections

**Comment by sparkingdark** [comment]
Is this open to work @burakcelebi and can i use python to wrap this issue.

**Comment by mdumandag** [comment]
Hi @sparkingdark 

Yes, this is still open to work. Roughly, what you should be doing is 
- add equivalent serializers of `IdentityProjection`, `SingleAttributeProjection`, and `MultiAttributeProjection`. You can look them up from the Java client. You don't have to implement `transform` method. Just the `get_factory_id`, `get_class_id`, `read_data` and `write_data` should be enough.
- add a method that looks like `def project(self, projection, predicate=None)` to the `hazelcast.proxy.map.Map`
- in the method, you should be using `map_project_codec` or `map_project_with_predicate_codec` depending on whether or not a predicate argument is passed. You can take a look at the other methods that take a predicate argument to get an idea.
- add documentation and tests.

Let me know if you have faced with any problems

**Comment by sparkingdark** [comment]
Thanks for this huge help and I will take a look to the codebase.

**Comment by burakcelebi** [comment]
Hi @sparkingdark! Looking forward to your contribution :) Please do not hesitate to ask for help anytime. Also, you can join our community on Slack: http://slack.hazelcast.com ❤️

**Comment by sparkingdark** [comment]
sorry for the delay I was pretty much busy with the college and assignments.But Now I start to work slowly on this issue.I hope will complete it.

@burakcelebi

**Comment by mdumandag** [comment]
No problem at all. 

By the way, in the meantime, we released a beta for the new major version (https://github.com/hazelcast/hazelcast-python-client/releases/tag/v4.0.0b1), so the codebase might look a little bit different to you but the things you should do is the same as I wrote in https://github.com/hazelcast/hazelcast-python-client/issues/203#issuecomment-703460717

If you have any problems or questions, you can write to me here, or via our [Slack channel ](https://slack.hazelcast.com/)

**Comment by yuce** [comment]
Hi @sparkingdark, thanks for your contribution. Did you have any progress on this issue?

**Comment by RobHam99** [comment]
I have submitted PR for this issue
