### ISSUE TITLE
Fast Aggregations

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-python-client#204]
Currently, Python Client has no support for Hazelcast's Aggregations which compute a value of some function (e.g sum or max) over the stored map entries. 

https://docs.hazelcast.org/docs/3.12.7/manual/html-single/index.html#fast-aggregations

**Comment by yuce** [comment]
@burakcelebi Is it OK to move this to 4.1 milestone?

**Comment by yuce** [comment]
The PR for this issue is at: https://github.com/hazelcast/hazelcast-python-client/pull/211

**Comment by yuce** [comment]
The implementation changed in Hazelcast 4, so we can disregard the linked PR.

**Comment by RobHam99** [comment]
I can work on this issue but I'm not sure where to start, thanks.

**Comment by yuce** [comment]
That's great! Would it be possible for you to join our Slack channel at Hazelcast Community https://hazelcastcommunity.slack.com/archives/python-client ? I guess it would be easier to talk about how to start there if that's OK for you.

**Comment by mdumandag** [comment]
Implemented by

https://github.com/hazelcast/hazelcast-python-client/pull/442
https://github.com/hazelcast/hazelcast-python-client/pull/445
