### ISSUE TITLE
Anchor links are not working on PyPI

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-python-client#210]
Anchor links in the PyPI (https://pypi.org/project/hazelcast-python-client/) are not working. It seems that it is known problem of PyPI. See: https://github.com/pypa/warehouse/issues/4064

As a solution, we can convert our markdown document to reStructuredText . It seems that PyPI supports anchor links in these documents.

**Comment by mdumandag** [comment]
Since #237 is merged for the master branch, I am setting the target milestone to 3.12.4

**Comment by yuce** [comment]
@mdumandag Links like: https://pypi.org/project/hazelcast-python-client/#configuration seems to work. Can we close this issue?

**Comment by mdumandag** [comment]
If you take a look at the documentation for the 3.12.3 release, you would see that they are not working. We need to either backport the documentation changes we did for the 4.x to 3.12.z branch or convert the README of the 3.12.z branch from markdown to reStructuredText
