### ISSUE TITLE
[TRACKING ISSUE] Added labels to ClientEndpoint#toString() method

### ISSUE THREAD

**Issue by hz-highfive** [hazelcast/hazelcast-python-client#319]
The tracking issue for the Java side PR.

**Added labels to ClientEndpoint#toString() method**

See https://github.com/hazelcast/hazelcast/pull/17181 for details.

---

Fixes https://github.com/hazelcast/hazelcast/issues/17178

**Comment by mdumandag** [comment]
`ClientInfo`, which is the Python side equivalent of this already has labels in his `__repr__` method
