### ISSUE TITLE
MapFeatNearCache invalidations with non-existent keys causes KeyError at runtime

### ISSUE THREAD

**Issue by justincsmith** [hazelcast/hazelcast-python-client#32]
Missing key-checks in [MapFeatNearCache](https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/proxy/map.py#L468) when invalidations occur.  If keys don't exist in the NearCache a `KeyError` is thrown.

**Comment by justincsmith** [comment]
Resolved this issue in #33

**Comment by asimarslan** [comment]
fixed by #39
