### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by Kilo59** [hazelcast/hazelcast-python-client#350]
Continuing to maintain backward-compatible support for python2.7 greatly increases the maintenance burden on contributors, scares off new contributors, forces additional dependencies, and prevents (or slows) the adoption of new features.

https://python3statement.org/

I would also recommend dropping support for python `3.5`, but IMO dropping `2.7` is a bigger deal.

**Comment by Kilo59** [comment]
I'm sure you are aware but dropping python2 support wouldn't break existing applications, it would just prevent them from using the very latest version unless they've updated to python3.

Downloads from pypi would just pull the latest python2 compatible version (for python2 users).

A first step could be to add a Warning to python2 users in the next release.

**Comment by yuce** [comment]
We've discussed about dropping Python 2.7 support just recently and I don't think we are ready to do that yet. So until that time comes we have to release the client for both 2 and 3. Thanks, adding a warning to Py 2 users is a good idea, we'll definitely consider it.

**Comment by hugovk** [comment]
Here's the pip installs for hazelcast-python-client from PyPI for July 2021:

| category | percent | downloads |
| -------- | ------: | --------: |
| 3.8      |  45.34% |     4,370 |
| 3.6      |  25.48% |     2,456 |
| 3.7      |  14.03% |     1,352 |
| null     |   7.74% |       746 |
| 2.7      |   5.38% |       519 |
| 3.9      |   2.02% |       195 |
| Total    |         |     9,638 |

Source: `pip install -U pypistats && pypistats python_minor hazelcast-python-client --last-month`
