### ISSUE TITLE
Provide better error messages on version mismatch between the client and the server

### ISSUE THREAD

**Issue by yuce** [hazelcast/hazelcast-python-client#355]

**Comment by RobHam99** [comment]
Hi, I would like to work on this issue. I am a beginner where should I start?

**Comment by RobHam99** [comment]
I think what I need to do is to is implement an error message on line 375 of errors.py, inside the class "VersionMismatchError". Can anyone confirm if this is correct and assign me the issue please. Thank you

**Comment by yuce** [comment]
Hi @RobHam99 Implementing this issue requires server-side changes, and we decided the outcome wouldn't worth the required effort. Would you be interested in working on another important issue? https://github.com/hazelcast/hazelcast-python-client/issues/204 Thanks for your contribution!
