### ISSUE TITLE
executor_service_sample.py sending Portable instead of Callable

### ISSUE THREAD

**Issue by padogrid** [hazelcast/hazelcast-python-client#407]
executor_service_sample.py example code is sending a Portable object instead of a Callable/Runnable. This example does not work. How do you create Callable/Runnable?

**Comment by mdumandag** [comment]
Hi @padogrid 

You have to register your `Callable`/`Runnable` classes on the Java side, before starting the members. What you send from the client is just a marker with some data. So, in the sample you mentioned, you are sending Portable class that holds a message from the client to server. 

On the server-side, you should have a Java class like below that does the actual work, which is also Portable.

```java
   class MessagePrinter implements Runnable, Portable {

      private String message;

      @Override
      public int getFactoryId() {
         return 1;
      }

      @Override
      public int getClassId() {
         return 9;
      }

      @Override
      public void writePortable(PortableWriter writer) throws IOException {
         writer.writeString("message", message);
      }

      @Override
      public void readPortable(PortableReader reader) throws IOException {
         message = reader.readString("message");
      }

      @Override
      public void run() {
         // Do something with the message here, on the Java side
         System.out.println(message);
      }
   }
```

Note that, it can also be `IdentifiedDataSerializable`.

**Comment by mdumandag** [comment]
Closing this. 

If you have further comments or questions, don't hesitate the reopen it back.
