### ISSUE TITLE
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray

### ISSUE THREAD

**Issue by arjunsingri** [hazelcast/hazelcast-python-client#50]
I repeatedly get the below error while connecting to the cluster member:

> 017-02-13 13:21:03,890	WARNING        	cluster                	_connect_to_cluster:119	6068   	140173885757184	Error connecting to Address(host=localhost, port=5701), attempt 2 of 2, trying again in 3 seconds
> Traceback (most recent call last):
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/cluster.py", line 115, in _connect_to_cluster
>     self._connect_to_address(address)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/cluster.py", line 145, in _connect_to_address
>     f = self._client.connection_manager.get_or_connect(address, self._authenticate_manager)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/connection.py", line 114, in get_or_connect
>     future = authenticator(connection).continue_with(self.on_auth, connection, address)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/cluster.py", line 142, in _authenticate_manager
>     return self._client.invoker.invoke_on_connection(request, connection).continue_with(callback)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/invocation.py", line 135, in invoke_on_connection
>     return self.invoke(Invocation(message, connection=connection), ignore_heartbeat)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/invocation.py", line 148, in invoke_smart
>     self._send(invocation, invocation.connection, ignore_heartbeat)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/invocation.py", line 223, in _send
>     connection.send_message(message)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/connection.py", line 282, in send_message
>     message.add_flag(BEGIN_END_FLAG)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/protocol/client_message.py", line 203, in add_flag
>     self.set_flags(self.get_flags() | flags)
>   File "/opt/ns/nsenv/local/lib/python2.7/site-packages/hazelcast/protocol/client_message.py", line 85, in get_flags
>     return struct.unpack_from(FMT_LE_UINT8, self.buffer, FLAGS_FIELD_OFFSET)[0]
> TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
>

**Comment by asimarslan** [comment]
This happens due to a [bug fixed in Python 2.7.4](https://bugs.python.org/issue10212).

Please use a latest version of python, we are currently running our test on python 2.7.6
