### ISSUE TITLE
removeAll implementation [API-1499]

### ISSUE THREAD

**Issue by alimertcan** [hazelcast/hazelcast-python-client#520]
hello can you please implement removeAll for python client [here is the link in java client](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/IMap.java#L456) 
thank you very much

**Comment by yuce** [comment]
Hi @alimertcan. This ticket is not a priority at the moment. But if you'd like to send a PR that implements this method, we would be glad to review and accept it in the client.
