### ISSUE TITLE
Pandas serialization code sample

### ISSUE THREAD

**Issue by yuce** [hazelcast/hazelcast-python-client#601]
A code sample which shows how to use the Python client with Pandas would be beneficial. The code sample would:

1. Create random Pandas data frames, and save them to a map. The keys of the map can be just strings. Choose an appropriate serialization method. The default "pickle" serialization may work, but it may be worthwhile to check others that could be used with the data frame, such as CSV, JSON.
2. Load one of the data frames from the map.
3. Plot a graph using the loaded data frame.

The data frames may be similar to the one at: https://pandas.pydata.org/docs/user_guide/10min.html#object-creation

**Comment by meltemtokgoz** [comment]
Hi 👋! 

Thanks for the `good first issue` tag! I have opened a PR which closes this issue https://github.com/hazelcast/hazelcast-python-client/pull/604. I would be glad if you could review @yuce.

**Comment by yuce** [comment]
Hi @meltemtokgoz, thanks for your contribution! We will review it ASAP.
