### ISSUE TITLE
Python 2.7.6: ImportError: No module named hzrc.client

### ISSUE THREAD

**Issue by thedevd** [hazelcast/hazelcast-python-client#74]
I am trying to run python client program using python 2.7.6 and I am getting this exception-

> Traceback (most recent call last):
>   File "main.py", line 6, in <module>
>     from hzrc.client import HzRemoteController
> ImportError: No module named hzrc.client

**Comment by sancar** [comment]
Hi @thedevd 
Remote controller is a tool we use internally.
Normally all examples should fallback to standard usage. The bug is to import `hzrc` at the top. Removing this line should easily fix your problem. I will send a pr for this.

**Comment by sancar** [comment]
@thedevd Thanks for the report.
