### ISSUE TITLE
High CPU usage caused by the Hazelcast client

### ISSUE THREAD

**Issue by Svedrin** [hazelcast/hazelcast-python-client#83]
Ever since we added the HZ client to one of our components, CPU usage of that component increased significantly. We could track it down to the `select` syscall, which is used by [`asyncore.loop` called by AsyncoreReactor](https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/reactor.py#L37).

CPU usage could be reduced by changing that call to `loop(count=1, timeout=0.1)`.

Our application itself makes heavy use of asyncore, so running two threads in one process, each with its own asyncore main loop in it, doesn't really make much sense. We'd appreciate being able to have the HZ client use our main loop, instead of living on its own thread. Would that be feasible?

**Comment by sancar** [comment]
@Svedrin 
Shouldn't we increase the count to reduce cpu usage ?  When count is one, the thread will wake up from the loop more frequently. Right now it wakes up every 100 millis. (1/10 of a second). For cpu, that should not be thathigh. When I run an idle client , it consumes at most 1% of a core in my machine.  What is the cpu usage you are seeing ? If it is high, then  can you describe the how you are using client ? May be we have another bug that cause this. 

Integrating async-core loops does not really seem possible to me.  
Is it done for similar libraries ? Do you know an example for that ? May be if we can find a smooth example that does this, we can offer the same thing.

**Comment by Svedrin** [comment]
@sancar 

> Right now it wakes up every 100 millis. (1/10 of a second).

actually it does not, because the timeout is set to `0.01`, which is 1/100 of a second. asyncore calls this method ten times in a row, which means that asyncore itself does come back only after 1/10 of a second as you're saying. But it did ten syscalls in the meantime, whereas a single one would have the same effect here.

So setting count to 1 (or omitting it completely) and setting the timeout to `0.1` (which is what you're trying to achieve) would mean that you only use a single syscall instead of 10.

And well, the HZ client is already using asyncore, so it's integrated already :P

**Comment by sancar** [comment]
Pr looks good to me. 

> We'd appreciate being able to have the HZ client use our main loop ?
By integrating I meant this one. How can we expose an API so that, HZ client can be part of an external loop.
