### ISSUE TITLE
PyPI has outdated version of Hazelcast python client

### ISSUE THREAD

**Issue by gattupalliaditya** [hazelcast/hazelcast-python-client#92]
We are using the latest version of the repository . If we clone and use the client it is working but not working if we install using pip.

@asimarslan @mdumandag

**Comment by asimarslan** [comment]
Hi @gattupalliaditya,
Our PyPi release is not outdated. We are currently working on very important improvement like python 3 support and SSL/TLS support. But we haven't complete the work yet.  
We may consider an early release that only includes python 3 support which community wants most I guess.

**Comment by mdumandag** [comment]
Hi @gattupalliaditya 
[Hazelcast Python Client 3.9](https://github.com/hazelcast/hazelcast-python-client/releases/tag/v3.9) is released and the [package](https://pypi.org/project/hazelcast-python-client/) in the PyPI is updated. So you can now install the updated client using pip.

I am clossing this issue. Thanks for your contribution.
